version: '3'
services:
  cypress:
    image: ${CYPRESS_IMAGE}
    volumes:
      - ./cypress:/app/cypress
      - ./cypress.config.ts:/app/cypress.config.ts
      - ./cypress/package.json:/app/package.json
    working_dir: /app
    command: bash -c "
      alias yarn=/usr/local/bin/yarn
      && alias cypress=/usr/local/bin/cypress
      && yarn install
      && yarn test"
    extra_hosts:
      - localhost:${MACHINE_HOST_IP}
    network_mode: host
  
# To set environment variables:
# Create a .env file at the same level as this file to set these values; example of .env file contents:
# MACHINE_HOST_IP=10.20.63.166
# CYPRESS_IMAGE=cypress:13.8.1

# NOTEs:
# 1) extra_hosts and network_mode "host" allow the container access to the local machine's network
# 2) It is recommended to pull the image locally to your machine 1st (makes things faster), though the 1st time you run this, the image will get pulled