# Args are defined in the Dockerfile before the FROM command
# Using these args will cause an image to be created with node, chrome, firefox and edge
# If unset, the image will be created with the default values
# To find the default values for ARGs, Refer to https://github.com/cypress-io/cypress-docker-images/blob/master/factory/factory.Dockerfile
# If ARG values are left empy, the related software will not be installed

# To build the image, run: docker build -f Dockerfile.cypress-11.2.0 -t cypress:11.2.0 .
# Note: there is a dot at the end of the build command

# Set node-module build version to the same one that comes bundled with cypress
# The easiest way to find that is to install cypress in test project localy and run command: npx cypress --version
ARG NODE_VERSION='16.16.0'
ARG YARN_VERSION='1.22.19'
ARG CYPRESS_VERSION='11.2.0'

# Skip browser installation for default image
ARG CHROME_VERSION=
ARG EDGE_VERSION=
ARG FIREFOX_VERSION=

# Use cypress/factory image provided by Cypress to customize build (Saved on ECR)
FROM cypress/factory

# Create app directory to map the cypress project
WORKDIR /
RUN mkdir app

# Each cypress folder should have a package.json file that contains the node modules needed to run the cypress tests ONLY (to keep the pipeline light)

# Run nothing
ENTRYPOINT []